version: '3.4'

services:
  oracle-xe:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-xe
    restart: always
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: "123"
    volumes:
      - oracle-data:/opt/oracle/oradata

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  oracle-data:
    driver: local