version: '3.3'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123!"
      # MSSQL_AUTHENTICATION: "SQL"
    ports:
      - "1433:1433"
    volumes:
      - my-volume:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  my-volume: