version: '3.3'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - my-volume:/var/opt/mssql
      - ./init.sql:/init.sql
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 10 && 
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P StrongPassword123! -d master -i /init.sql &&
      wait"
      
volumes:
  my-volume: